name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest 

    env:
      MODE: ${{ secrets.MODE }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      REMOTE_DIR: ${{ secrets.REMOTE_DIR }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/ --maxfail=3 --disable-warnings -q 

    - name: View test results
      run: |
        echo "Test results"
