name: Multi-Platform Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            executable: termux_vsbridge.exe
            tasks: tasks-windows.json
            path_separator: \\
            zip_name: termux_vsbridge-windows.zip
            archive_cmd: powershell -Command "Compress-Archive -Path dist\\.vscode,dist\\project_file -DestinationPath dist\\$ZIP_NAME"
            artifact_name: vsbridge-windows
          - os: ubuntu-latest
            executable: termux_vsbridge
            tasks: tasks-linux.json
            path_separator: /
            zip_name: termux_vsbridge-linux.zip
            archive_cmd: zip -r dist/$ZIP_NAME dist/.vscode dist/project_file
            artifact_name: vsbridge-linux
          - os: macos-latest
            executable: termux_vsbridge
            tasks: tasks-macos.json
            path_separator: /
            zip_name: termux_vsbridge-macos.zip
            archive_cmd: zip -r dist/$ZIP_NAME dist/.vscode dist/project_file
            artifact_name: vsbridge-macos

    env:
      EXECUTABLE: ${{ matrix.executable }}
      TASKS: ${{ matrix.tasks }}
      PATH_SEPARATOR: ${{ matrix.path_separator }}
      ZIP_NAME: ${{ matrix.zip_name }}
      ARTIFACT_NAME: ${{ matrix.artifact_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install PyInstaller
        run: pip install pyinstaller
        shell: bash

      - name: Install Requirements
        run: pip install -r requirements.txt
        shell: bash

      - name: Build Executable with PyInstaller
        run: pyinstaller --onefile --name=termux_vsbridge termux_vsbridge$PATH_SEPARATORrun.py
        shell: bash

      - name: Prepare VSCode Folder
        run: |
          mkdir -p dist/.vscode
          mkdir -p dist/project_file
          mv dist/$EXECUTABLE dist/.vscode/$EXECUTABLE
          cp vscode-tasks/$TASKS dist/.vscode/tasks.json
        shell: bash

      - name: Build ZIP Archive
        run: ${{ matrix.archive_cmd }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: $ARTIFACT_NAME
          path: dist/$ZIP_NAME

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded artifacts
        run: ls -R artifacts
        shell: bash

      - name: Check if tag exists
        run: |
          if git rev-parse "${{ github.event.inputs.release_version }}" >/dev/null 2>&1; then
            echo "Tag ${{ github.event.inputs.release_version }} already exists"
            exit 1
          fi
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          name: Termux VSBridge ${{ github.event.inputs.release_version }}
          files: |
            artifacts/vsbridge-windows/termux_vsbridge-windows.zip
            artifacts/vsbridge-linux/termux_vsbridge-linux.zip
            artifacts/vsbridge-macos/termux_vsbridge-macos.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}